[package]
name = "erofs-builder"
version = "0.1.1"
edition = "2021"
description = "EROFS image writer"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["io-util", "fs", "rt-multi-thread", "macros"] }
crc32c = "0.6"
rand = "0.8"
clap = { version = "4", features = ["derive"], optional = true }

[features]
default = []

[[bin]]
name = "mkfs-sample"
required-features = ["clap"]
