[package]
name = "erofs-rs"
version = "0.1.0"
edition = "2021"
description = "EROFS image writer"
license = "MIT"

[dependencies]
tokio-stream = "0.1"
futures-core = "0.3"
futures-sink = "0.3"
crc32c = "0.6"
rand = "0.8"
tokio = { version = "1", features = ["full"], optional = true }
clap = { version = "4", features = ["derive"], optional = true }

[features]
default = []
tokio = ["dep:tokio"]

[[bin]]
name = "mkfs-sample"
required-features = ["tokio", "clap"]
